name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true 
      next:
        description: 'Next version'
        required: false 

jobs:
  release:
    # This job has been inspired by the moditect release (https://github.com/moditect/moditect/blob/main/.github/workflows/release.yml)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven

      - name: Set release version
        id: version
        run: |
          RELEASE_VERSION=${{ github.event.inputs.version }}
          NEXT_VERSION=${{ github.event.inputs.next }}
          PLAIN_VERSION=`echo ${RELEASE_VERSION} | awk 'match($0, /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)/) { print substr($0, RSTART, RLENGTH); }'`
          COMPUTED_NEXT_VERSION="${PLAIN_VERSION}-SNAPSHOT"
          if [ -z $NEXT_VERSION ]
          then
            NEXT_VERSION=$COMPUTED_NEXT_VERSION
          fi
          mvn -ntp -B versions:set versions:commit -DnewVersion=$RELEASE_VERSION -DgenerateBackupPoms=false
          git config --global user.email "${{ vars.GH_BOT_EMAIL }}"
          git config --global user.name "GitHub Action"
          git commit -a -m "Releasing version $RELEASE_VERSION"
          git push
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "PLAIN_VERSION=$PLAIN_VERSION" >> $GITHUB_ENV

      - name: Stage
        run: |
          export GPG_TTY=$(tty)
          mvn -ntp -B package

      - name: Create ZIP file
        run: |
          mkdir -p release
          zip -r release/java-build-${{ env.RELEASE_VERSION }}.zip target/*

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Lambda Ext Release ${{ env.RELEASE_VERSION }}
          draft: false 
          prerelease: false 

      - name: Upload Java build ZIP to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/java-build-${{ env.RELEASE_VERSION }}.zip
          asset_name: java-build-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip

      - name: Reset NEXT_RELEASE_CHANGELOG.md
        run: |
          echo -e "### Features\n\n### Enhancements\n\n### Bugs\n\n### Documentation\n\n### Build\n" > NEXT_RELEASE_CHANGELOG.md

      - name: Set next version
        run: |
          mvn -ntp -B versions:set versions:commit -DnewVersion=${{ env.NEXT_VERSION }} -DgenerateBackupPoms=false
          git config --global user.email "${{ vars.GH_BOT_EMAIL }}"
          git config --global user.name "GitHub Action"
          git commit -a -m "Next version ${{ env.NEXT_VERSION }}"
          git push
